[versions]
kakao_sdk = "2.20.1"
google_gms = "4.3.15"
firebase_auth = "22.0.0"
firebase_bom = "32.0.0"
gms_auth = "20.5.0"

[libraries]
kakao_sdk = { group = "com.kakao.sdk", name = "v2-user",  version.ref = "kakao_sdk" }
google_gms = { group = "com.google.gms", name = "google-services" , version.ref = "google_gms" }
firebase-auth = { group = "com.google.firebase", name = "firebase-auth", version.ref = "firebase_auth" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase_bom" }
gms-auth = { group = "com.google.android.gms", name = "play-services-auth" ,version.ref = "gms_auth" }

[plugins]
